import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowUpRight, FlaskConical, Info } from 'lucide-react'
import { PreviewChart, type PlotSeries, type PlotPoint } from './PreviewChart'
import './backtest-preview.css'
import { RiskEnsemblePanels } from './RiskEnsemblePanels'

type Row={day:number;nav:number;wealth:number;return:number;drawdown:number;price:number;shares:number;cash:number;market_value:number;receivables:number;cash_stack_top:number;nav_stack_top:number;exposure:number;target_exposure:number}
type Trade={day:number;side:string;quantity:number;price:number;reason?:string;limit_price?:number}
type Stats={histogram:PlotPoint[];normal:PlotPoint[];quantile_05:number;tail_mean_05:number;var_95_loss:number;cvar_95_loss:number;skewness:number|null;excess_kurtosis:number|null}
type Summary={total_return:number;max_drawdown:number;annualized_volatility:number;sharpe:number|null;calmar:number|null;turnover:number;total_fees:number;average_exposure:number;fills:number;unfilled:number;underwater_sessions:number;terminal_underwater_sessions:number;right_censored:boolean}
type Series={id:string;name:string;color:string;rows:Row[];trades:Trade[];unfilled:Trade[];statistics:Stats;summary:Summary}
type Scenario={id:string;name:string;series:Series[];correlation:number[][];high_volatility:{from:number;to:number;label:string};price_diagnostics:{returns:PlotPoint[];acf:PlotPoint[];acf_reference:number;rolling_volatility:PlotPoint[]};invariants:{status:string;strategy_sessions:number;benchmark_sessions:number}}
type Demo={schema_version:number;real_market_data:boolean;research_status:string;contract:{seed:number};scenarios:Scenario[];acceptance_fixture:{checks:unknown[];flow_comparison:{period_end:string;period_start:string};tables:{daily_nav:{date:string;nav:string;cash:string;market_value:string;receivables:string;external_flow:string}[]}}}
const percent=(n:number)=>`${(n*100).toFixed(2)}%`
const money=(n:number)=>n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const amount=(n:number)=>n.toLocaleString('zh-CN',{maximumFractionDigits:0})
const num=(n:number|null)=>n===null?'不可用':n.toFixed(2)
const dayLabel=(n:number)=>n===0?'t0':`D${Math.round(n).toString().padStart(3,'0')}`
const reasons:Record<string,string>={outside_order_limit:'开盘价超出限价',halted:'停牌',price_limit_blocked:'涨跌停阻断',insufficient_cash:'资金不足'}
export function BacktestPreviewPage(){
 const[data,setData]=useState<Demo|null>(null),[error,setError]=useState('')
 const[scenarioId,setScenario]=useState('steady'),[visible,setVisible]=useState(['a','b','c'])
 const[mode,setMode]=useState<'wealth'|'nav'>('wealth'),[windowId,setWindow]=useState('all')
 const[selected,setSelected]=useState(252),[assetId,setAsset]=useState('a')
 useEffect(()=>{const old=document.title;document.title='策略对比 · Factor Matrix';return()=>{document.title=old}},[])
 useEffect(()=>{const c=new AbortController();fetch('/demo-backtest/v3/preview.json',{signal:c.signal}).then(r=>{if(!r.ok)throw new Error(`数据加载失败 ${r.status}`);return r.json()}).then((d:Demo)=>{if(d.schema_version!==3||d.real_market_data!==false||d.research_status!=='not_eligible')throw new Error('展示数据标识不匹配');setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[])
 const scenario=data?.scenarios.find(s=>s.id===scenarioId),asset=scenario?.series.find(s=>s.id===assetId)
 const lo=windowId==='last63'?190:windowId==='last126'?127:0,hi=windowId==='first10'?10:252
 const inside=(d:number)=>d>=lo&&d<=hi
 const changeWindow=(v:string)=>{setWindow(v);const l=v==='last63'?190:v==='last126'?127:0,h=v==='first10'?10:252;setSelected(d=>Math.max(l,Math.min(h,d)))}
 const plot=(key:keyof Row):PlotSeries[]=>(scenario?.series??[]).filter(s=>s.id==='benchmark'||visible.includes(s.id)).map(s=>({id:s.id,name:s.name,color:s.color,dash:s.id==='benchmark',points:s.rows.filter(r=>inside(r.day)).map(r=>({x:r.day,y:r[key]}))}))
 const one=(key:keyof Row,name=asset?.name??'',color=asset?.color??'#346779'):PlotSeries=>({id:key,name,color,points:(asset?.rows??[]).filter(r=>inside(r.day)).map(r=>({x:r.day,y:r[key]}))})
 const point=asset?.rows.find(r=>r.day===selected)
 const ticks=windowId==='first10'?[0,1,2,4,6,8,10]:undefined
 const metrics:[string,(s:Summary)=>string][]=[['累计收益',s=>percent(s.total_return)],['最大回撤',s=>percent(s.max_drawdown)],['年化波动',s=>percent(s.annualized_volatility)],['Sharpe（零基准）',s=>num(s.sharpe)],['Calmar',s=>num(s.calmar)],['累计单边换手',s=>percent(s.turnover)],['总交易费用 / 元',s=>money(s.total_fees)],['平均日终仓位',s=>percent(s.average_exposure)],['成交 / 未成交',s=>`${s.fills} / ${s.unfilled}`],['最长水下区间',s=>s.right_censored&&s.terminal_underwater_sessions===s.underwater_sessions?`≥${s.underwater_sessions} 日（未修复）`:`${s.underwater_sessions} 日`],['期末水下区间',s=>s.right_censored?`≥${s.terminal_underwater_sessions} 日（未修复）`:'已修复']]
 return <div className="bp-page"><nav className="bp-nav"><a className="bp-brand" href="#/research"><span>Factor<span className="bp-brand-serif">Matrix</span></span><small>RESEARCH & ANALYTICS</small></a><div className="bp-nav-links"><a href="#bp-comparison">策略对比</a><a href="#bp-execution">成交与仓位</a><a href="#bp-diagnostics">统计诊断</a><a href="#bp-ensemble">模拟分布</a><a href="#bp-risk">风险接入</a></div><a className="bp-back" href="#/research"><ArrowLeft size={15}/>返回工作台</a></nav>
 <main className="bp-body"><header className="bp-intro"><span className="bp-kicker">STRATEGY COMPARISON</span><h1>策略对比</h1><p>同一行情、相同初始资金与交易规则，比较三种仓位决策。</p><div className="bp-demo"><FlaskConical size={14}/><strong>模拟压力测试</strong><span>252 日 · 非真实行情 · 三个手工情景不代表概率分布</span></div></header>
 {error?<div className="bp-error" role="alert">{error}</div>:!scenario||!asset||!point?<div className="bp-loading">载入固定样本…</div>:<>
 <div className="bp-section-heading" id="bp-comparison"><span>01 / STRATEGY COMPARISON</span><h2>净值与回撤</h2><p>每个情景共享一条价格路径。基准采用同一执行模型，首次买入可负担股数后持有，余款留现金。</p></div>
 <div className="bp-scenario-tabs" role="tablist" aria-label="压力情景">{data!.scenarios.map(s=><button key={s.id} role="tab" aria-selected={s.id===scenarioId} className={s.id===scenarioId?'active':''} onClick={()=>setScenario(s.id)}>{s.name}</button>)}</div>
 <section className="bp-surface"><div className="bp-toolbar"><div className="bp-segment"><button aria-pressed={mode==='wealth'} className={mode==='wealth'?'active':''} onClick={()=>setMode('wealth')}>单位净值</button><button aria-pressed={mode==='nav'} className={mode==='nav'?'active':''} onClick={()=>setMode('nav')}>账户金额</button></div><label>展示区间 <select aria-label="展示区间" value={windowId} onChange={e=>changeWindow(e.target.value)}><option value="all">全部 252 日</option><option value="first10">期初 10 日（核对 t0 / D1）</option><option value="last126">末尾 126 日</option><option value="last63">末尾 63 日</option></select></label></div>
 <div className="bp-chart-layout"><div><PreviewChart title="同一行情的策略与买入持有净值" series={plot(mode)} format={mode==='wealth'?n=>n.toFixed(3):amount} selected={selected} onSelect={setSelected} height={320} hideReadout xTicks={ticks}/><div className="bp-legend bp-unified-legend"><span>{dayLabel(selected)}</span>{scenario.series.map(s=><button key={s.id} disabled={s.id==='benchmark'} aria-pressed={s.id==='benchmark'||visible.includes(s.id)} className={s.id!=='benchmark'&&!visible.includes(s.id)?'muted':''} onClick={()=>setVisible(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}><i style={{background:s.color}}/>{s.name} <b>{mode==='wealth'?s.rows[selected].wealth.toFixed(3):money(s.rows[selected].nav)}</b></button>)}</div></div><aside className="bp-explainer"><span>SAME MARKET</span><h3>比较仓位决策</h3><p>A 固定 80%；B 在上一收盘价高于过去 20 日均价时取 80%，否则 20%，不足 20 日取 20%；C 固定 40%。每 21 日调仓。</p><p>所有策略共享开盘价、收盘价、停牌和费用模型。基准不做期末清仓。</p><small>t0：100,000 元现金、零持仓；最早 D1 开盘成交。</small></aside></div>
 <div className="bp-scrubber"><label htmlFor="bp-day">观察日 <b>{dayLabel(selected)}</b></label><input id="bp-day" type="range" aria-label="查看观测日" min={lo} max={hi} value={selected} onChange={e=>setSelected(Number(e.target.value))}/></div></section>
 <section className="bp-surface"><div style={{overflowX:'auto'}}><table className="bp-audit-table"><caption>全样本指标 · 252 日（切换展示区间不重算）</caption><thead><tr><th>指标</th>{scenario.series.map(s=><th key={s.id} style={{color:s.color}}>{s.name}</th>)}</tr></thead><tbody>{metrics.map(([name,format])=><tr key={name}><th>{name}</th>{scenario.series.map(s=><td key={s.id}>{format(s.summary)}</td>)}</tr>)}</tbody></table></div><p className="bp-note">年化按 252 日；Sharpe 使用净值日收益均值 / 样本标准差 × √252，零基准收益；Calmar = 年化复合收益 / 最大回撤。换手 = 各笔成交额 / 前一日净值之和（买卖均计，不除以二）。≥ 表示截至样本末仍未修复的右删失时长。</p></section>
 <section className="bp-surface bp-chart-layout"><PreviewChart title="策略与基准日终回撤" series={plot('drawdown')} format={percent} selected={selected} onSelect={setSelected} area zero xTicks={ticks}/><aside className="bp-explainer"><h3>日终回撤</h3><p>基准包含 t0。所有策略按日终外部资金流中和收益；主样本没有出入金。</p><p>主路径不变量：{scenario.invariants.status==='passed'?'252 × 3 日通过；基准另 252 日通过。':'尚未通过。'}包含净值勾稽、非负现金、买入申报单位、T+1、停牌及不利方向涨跌停阻断。</p></aside></section>
 <div className="bp-section-heading" id="bp-execution"><span>02 / EXECUTION</span><h2>成交与仓位</h2><p>实心三角表示成交；空心三角表示尝试执行但未成交，纵坐标为该时点开盘报价。</p></div>
 <section className="bp-surface"><div className="bp-asset-tabs" aria-label="选择策略">{scenario.series.map(s=><button key={s.id} aria-pressed={s.id===assetId} className={s.id===assetId?'active':''} onClick={()=>setAsset(s.id)}><i style={{background:s.color}}/>{s.name}</button>)}</div>
 <div className="bp-chart-layout"><div><PreviewChart title="共享价格与策略成交" series={[one('price','共享收盘价')]} xTicks={ticks} selected={selected} onSelect={setSelected} markers={[...asset.trades.filter(t=>inside(t.day)).map(t=>({x:t.day,y:t.price,side:t.side,quantity:t.quantity})),...asset.unfilled.filter(t=>inside(t.day)).map(t=>({x:t.day,y:t.price,side:t.side,quantity:t.quantity,unfilled:true,reason:reasons[t.reason??'']??t.reason}))]}/>
 <PreviewChart title="资产构成堆叠面积" series={[
 {id:'market',name:'持仓市值',color:asset.color,stack:true,points:asset.rows.filter(r=>inside(r.day)).map(r=>({x:r.day,y:r.market_value,y0:0,value:r.market_value}))},
 {id:'cash',name:'现金',color:'#b8cbbd',stack:true,points:asset.rows.filter(r=>inside(r.day)).map(r=>({x:r.day,y:r.cash_stack_top,y0:r.market_value,value:r.cash}))},
 {id:'receivables',name:'应收款',color:'#d5b878',stack:true,points:asset.rows.filter(r=>inside(r.day)).map(r=>({x:r.day,y:r.nav_stack_top,y0:r.cash_stack_top,value:r.receivables}))}
 ]} selected={selected} onSelect={setSelected} format={amount} zero height={220} xTicks={ticks}/>
 <PreviewChart title="目标与实际仓位" series={[{...one('target_exposure','当日目标','#bc9062'),step:true,dash:true},one('exposure','实际日终仓位')]} selected={selected} onSelect={setSelected} format={percent} fixedDomain={[0,1]} height={190} xTicks={ticks}/></div>
 <aside className="bp-explainer"><h3>{asset.name}</h3><dl><dt>观察日</dt><dd>{dayLabel(selected)}</dd><dt>收盘价</dt><dd>{money(point.price)}</dd><dt>持仓股数</dt><dd>{point.shares}</dd><dt>现金</dt><dd>{money(point.cash)}</dd><dt>净值</dt><dd>{money(point.nav)}</dd></dl><p>面积总高度等于净值。目标仓位为上一收盘确定、当日生效的目标；实际仓位为日终市值 / 净值。偏差同时包含价格波动、手数、费用及未成交影响。</p><small>观察点之间的连线不代表盘中路径。切换“期初 10 日”可分辨 t0 和 D1。</small></aside></div>
 <details className="bp-method"><summary>未成交记录 · {asset.unfilled.length} 笔</summary>{asset.unfilled.length?<table className="bp-audit-table"><thead><tr><th>日</th><th>方向 / 股数</th><th>开盘报价</th><th>限价</th><th>原因</th></tr></thead><tbody>{asset.unfilled.map((t,i)=><tr key={i}><td>{dayLabel(t.day)}</td><td>{t.side==='buy'?'买':'卖'} / {t.quantity}</td><td>{money(t.price)}</td><td>{money(t.limit_price!)}</td><td>{reasons[t.reason??'']??t.reason}</td></tr>)}</tbody></table>:<p>本策略在该情景没有未成交订单。执行压力情景预设 D64 跳空、D127 停牌。</p>}</details></section>
 <div className="bp-section-heading" id="bp-diagnostics"><span>03 / DESCRIPTIVE STATISTICS</span><h2>统计诊断</h2><p>收益分布使用所选策略的净值收益；波动诊断使用全体策略共享的价格收益。</p></div>
 <section className="bp-surface bp-chart-layout"><div className="bp-heatmap-wrap"><div className="bp-heatmap" role="table" aria-label="同市场策略与基准收益相关性" style={{gridTemplateColumns:'100px repeat(4,1fr)'}}><span/>{scenario.series.map(s=><b key={s.id}>{s.id==='benchmark'?'基准':s.id.toUpperCase()}</b>)}{scenario.correlation.map((row,i)=><div className="bp-heat-row" role="row" key={i}><b>{scenario.series[i].name}</b>{row.map((v,j)=><span role="cell" key={j} title={`${scenario.series[i].name} / ${scenario.series[j].name}: ${v.toFixed(3)}`} style={{background:v>=0?`rgba(52,103,121,${Math.abs(v)})`:`rgba(174,91,95,${Math.abs(v)})`,color:Math.abs(v)>.55?'white':'#405762'}}>{v.toFixed(2)}</span>)}</div>)}</div><div className="bp-heat-scale"><span>−1</span><i style={{background:'linear-gradient(90deg,#ae5b5f,#fff,#346779)'}}/><span>+1</span></div></div><aside className="bp-explainer"><h3>策略收益相关性</h3><p>同一组 252 个观测日，三个策略及基准的净值日收益相关系数。发散色标覆盖 −1 至 +1。</p></aside></section>
 <section className="bp-surface bp-chart-layout"><PreviewChart title="策略日收益直方密度与正态参考" series={[{id:'hist',name:asset.name,color:asset.color,points:asset.statistics.histogram,step:true},{id:'normal',name:'同均值同方差正态',color:'#a3aaa6',points:asset.statistics.normal,dash:true}]} xDomain={[-.06,.06]} xTicks={[-.05,-.025,0,.025,.05]} xLabel={percent} format={n=>n.toFixed(0)} zero references={[{x:asset.statistics.quantile_05,label:'5% 分位',color:'#b77a8a'},{x:asset.statistics.tail_mean_05,label:'尾部均值',color:'#92704c'}]}/><aside className="bp-explainer"><h3>{asset.name} · 净值日收益</h3><p>阶梯线为固定分箱密度，灰虚线为同均值、同样本方差的正态参考；不是分布拟合结论。</p><dl><dt>VaR 95%（损失）</dt><dd>{percent(asset.statistics.var_95_loss)}</dd><dt>CVaR 95%（损失）</dt><dd>{percent(asset.statistics.cvar_95_loss)}</dd><dt>偏度</dt><dd>{num(asset.statistics.skewness)}</dd><dt>超额峰度</dt><dd>{num(asset.statistics.excess_kurtosis)}</dd></dl><small>VaR = −经验 5% 分位；CVaR = −分位以下收益均值。偏度、超额峰度采用样本中心矩。</small></aside></section>
 <section className="bp-surface bp-chart-layout"><PreviewChart title="共享价格绝对日收益自相关" series={[{id:'price-acf',name:'价格绝对收益 ACF',color:'#346779',points:scenario.price_diagnostics.acf}]} xTicks={[1,5,10,15,20]} xLabel={n=>String(n)} horizontalBand={[-scenario.price_diagnostics.acf_reference,scenario.price_diagnostics.acf_reference]} zero/><aside className="bp-explainer"><h3>价格波动持续性</h3><p>计算对象：共享价格的收盘到收盘收益绝对值。没有策略仓位调制。</p><p>阴影为 ±1.96/√252 ≈ ±0.123 的白噪声逐滞后近似参考带，不是多重检验后的显著性结论。</p></aside></section>
 <section className="bp-surface bp-chart-layout"><PreviewChart title="价格日收益与20日滚动波动率" series={[{id:'price-return',name:'价格日收益',color:'#afbac0',points:scenario.price_diagnostics.returns.filter(p=>inside(p.x))},{id:'rolling-vol',name:'20日滚动日波动率',color:'#346779',points:scenario.price_diagnostics.rolling_volatility.filter(p=>inside(p.x))}]} format={percent} selected={selected} onSelect={setSelected} fixedDomain={[-.075,.075]} spans={[scenario.high_volatility]} xTicks={ticks}/><aside className="bp-explainer"><h3>价格波动聚集</h3><p>深色线为过去 20 个价格日收益的样本标准差，未年化。前 19 日不补零、不用未来数据。</p><p>浅色阴影标出生成器预设的高波动区间 D87–D138。三个手工情景是压力测试，不是概率分布。</p></aside></section>
 <RiskEnsemblePanels strategyId={assetId} reference={{...asset,name:scenario.name}} strategies={scenario.series} onStrategyChange={setAsset}/>
 <details className="bp-method"><summary><Info size={15}/>账务与口径验收 · {data!.acceptance_fixture.checks.length} 项通过</summary><p>原 10 日账务样本保持不变。D6 入金发生在当日收益形成后、日终估值之前；按期末资金流中和，累计收益 5.7679%。若同一笔入金改为当日开盘前到账，则同一组日终净值按日初口径得到约 4.2264%。这两种约定不能混用。</p><p>另设资金充足的独立涨停买单分支：前收 9、开盘 9.90，拒绝买入且不扣费用。原样本 D5 剩余现金仅 676.79 元，不足以提交 100 股涨停买单，不能把资金不足误当涨停阻断。</p><div style={{overflowX:'auto'}}><table className="bp-audit-table"><thead><tr><th>日</th><th>现金</th><th>市值</th><th>应收款</th><th>外部资金流</th><th>净值</th></tr></thead><tbody>{data!.acceptance_fixture.tables.daily_nav.map((r,i)=><tr key={r.date}><td>{dayLabel(i)}</td><td>{r.cash}</td><td>{r.market_value}</td><td>{r.receivables}</td><td>{r.external_flow}</td><td>{r.nav}</td></tr>)}</tbody></table></div></details>
 <details className="bp-method"><summary><Info size={15}/>数据、费用与统计口径</summary><p>固定种子 {data!.contract.seed}，t0 与 D001–D252 是合成观测。三种策略共享每个情景的价格、日历和交易规则；压力情景另有固定 D64 开盘跳空 +3% 和 D127 停牌。该版本独立发布，不覆盖旧版研究工件。</p><p>佣金 0.01854%、最低 5 元；卖出印花税 0.05%、双向过户费 0.001%。按订单累计、分项四舍五入至分，佣金假设包含交易所费用；券商归并舍入尚待交割单核验。未计红利税，账户类型与持股期限税务模型未接入。采用未复权价和显式公司行为账务。外部资金流配置为日终，日初口径另行测试。</p><p>本页所有指标为描述性统计。模拟分布按独立版本的 1,000 条合成行情逐条重跑交易与账务；当前未执行真实行情 bootstrap。</p><a href="/demo-backtest/v3/_MANIFEST.json" target="_blank" rel="noreferrer">数据 manifest <ArrowUpRight size={13}/></a></details>
 </>}
 <footer className="bp-footer"><span>FACTOR MATRIX / STRATEGY COMPARISON</span><span>合成数据 · 不用于研究准入</span></footer></main></div>
}
